// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKELncbuEsOtj73Ho_CD2h1Wn9vhZgoVg',
    appId: '1:1042367058729:web:e1b230cdd2103f3d2a1d38',
    messagingSenderId: '1042367058729',
    projectId: 'chat-app-1ea85',
    authDomain: 'chat-app-1ea85.firebaseapp.com',
    storageBucket: 'chat-app-1ea85.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN2NweOIk057K1p5JmwSlP0s2G37ULTbg',
    appId: '1:1042367058729:android:01a0e7d4115dc53f2a1d38',
    messagingSenderId: '1042367058729',
    projectId: 'chat-app-1ea85',
    storageBucket: 'chat-app-1ea85.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdv_TnXRHJXIbMvJtq-x19VDeKjy8eESc',
    appId: '1:1042367058729:ios:01b46531f7f6bb622a1d38',
    messagingSenderId: '1042367058729',
    projectId: 'chat-app-1ea85',
    storageBucket: 'chat-app-1ea85.firebasestorage.app',
    iosBundleId: 'com.elipair.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdv_TnXRHJXIbMvJtq-x19VDeKjy8eESc',
    appId: '1:1042367058729:ios:49d1b61d88a1dccd2a1d38',
    messagingSenderId: '1042367058729',
    projectId: 'chat-app-1ea85',
    storageBucket: 'chat-app-1ea85.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKELncbuEsOtj73Ho_CD2h1Wn9vhZgoVg',
    appId: '1:1042367058729:web:3948611ccbe4b1172a1d38',
    messagingSenderId: '1042367058729',
    projectId: 'chat-app-1ea85',
    authDomain: 'chat-app-1ea85.firebaseapp.com',
    storageBucket: 'chat-app-1ea85.firebasestorage.app',
  );
}
